### PR TITLE
Add support for multiple data types

### PR DESCRIPTION
**Pull request by edenhaus**
Restructure all commands and messages to support multiple data types.

### CODE REVIEW

**Comment by edenhaus** [comment]
@sandervankasteel What do you think about this change?

The implementation of which model supports what is coming in a follow-up PR.

**Comment by sandervankasteel** [comment]
> @sandervankasteel What do you think about this change?
> 
> The implementation of which model supports what is coming in a follow-up PR.


For an initial base of the new architecture, I can definitely see this working! :smile:

**Comment by sandervankasteel** [comment]
@edenhaus what the your proposed action plan for this? 

Do you wanna merge this PR + plus the functionality for model specific implementations first and then I update my PR for the new functionality? Or would be better for me to already start implemented the XML commands based on this PR?

**Comment by edenhaus** [comment]
@sandervankasteel I have created the new branch `dev`, use this branch as base for your changes. You can start to implemented the new commands 😊

In the meantime I work on the model specific support PR

**Pull request merged**
