### PR TITLE
Add X1 Omni support (1vxt52)

### PR DESCRIPTION
**Pull request by gdgib**
I've got an X1 Omni (1vxt52), and obviously with the recent changes it no longer shows up in HA.  My bot seems to work well enough with both the X2 Omni and X1 Turbo files, but I think the X1 Turbo is closer in feature set, both according to marketing and testing.

To test, I just hacked the symlink into my running HA instance and restarted HA.  2o4lnm seems a little better fit, but e6ofmn handled at least the basics, FWIW.

I admit I would LOVE a guide on how to properly determine the features in this file, because in the absence of that I'm "hacking" more than "coding" and that makes me justifiably nervous.  Just because everything works doesn't mean it works for the right reasons, you know?

Let me know if you've got other steps I can take to make sure this is really working, please!

## Summary by CodeRabbit

- **New Features**
	- Introduced comprehensive configuration for a robotic vacuum device, enhancing battery management, cleaning operations, and custom command execution.
	- Added functionalities for fan speed control, lifespan management of components, and advanced mapping features.
	- Enabled network information retrieval and sound playback capabilities.
	- Implemented settings management for features like carpet auto fan boost and voice assistant state.
	- Enhanced state and statistics reporting for improved user insights.
	- Added support for a new device identifier, ensuring it is included in model loading verification.

### CODE REVIEW

**Comment by gdgib** [comment]
If anyone spots this and is willing to risk completely breaking their HA install here are the steps for testing this locally on HAOS:

* Open HomeAssistant CLI (e.g. the console), and run `login` to get a shell prompt
* `docker ps | grep homeassistant:` - yes the colon is part of it!
* `docker exec -it <CONTAINERID> sh` - get the container ID from the start of the output above, it's a hex string
* `cd /usr/local/lib/python3.13/site-packages/deebot_client/hardware/deebot`
* `ln -svfT 2o4lnm.py 1vxt52.py`
* Restart home assistant

**Comment by edenhaus** [comment]
> I admit I would LOVE a guide on how to properly determine the features in this file, because in the absence of that I'm "hacking" more than "coding" and that makes me justifiably nervous. Just because everything works doesn't mean it works for the right reasons, you know?

There is no "correct" way to determine the features properly as Ecovacs is not providing any public API documentation. Therefore, I used the "try and error" approach in the past. I'm also logging the traffic between the app and the Ecovacs server to see if I can spot new commands but for that you need a man in the middle proxy setup, which is also not trivial

**Comment by edenhaus** [comment]
Please fix the tests by applying:

```diff
diff --git a/tests/hardware/test_init.py b/tests/hardware/test_init.py
index b4039cb..24bf9df 100644
--- a/tests/hardware/test_init.py
+++ b/tests/hardware/test_init.py
@@ -250,6 +250,7 @@ def test_all_models_loaded() -> None:
     """Test that all models are loaded."""
     _load()
     assert list(DEVICES) == [
+        "1vxt52",
         "2ap5uq",
         "2o4lnm",
         "4vhygi",
```


or give me push access to your repo

**Comment by marcolino7** [comment]
> * cd /usr/local/lib/python3.13/site-packages/deebot_client/hardware/deebot

I tried this to make it work my Deebot T9, but I got an error:

```
2024-12-05 11:54:34.874 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry xxxxxxxxxxx@gmail.com for ecovacs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/ecovacs/__init__.py", line 29, in async_setup_entry
    await controller.initialize()
  File "/usr/src/homeassistant/homeassistant/components/ecovacs/controller.py", line 81, in initialize
    devices = await self._api_client.get_devices()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/deebot_client/api_client.py", line 81, in get_devices
    if static_device_info := await get_static_device_info(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        device["class"]
        ^^^^^^^^^^^^^^^
    ):
    ^
  File "/usr/local/lib/python3.13/site-packages/deebot_client/hardware/deebot/__init__.py", line 32, in get_static_device_info
    await asyncio.get_event_loop().run_in_executor(None, _load)
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.13/site-packages/deebot_client/hardware/deebot/__init__.py", line 26, in _load
    importlib.import_module(full_package_name)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'deebot_client.hardware.deebot.1vxt52'
```

How can I check correct file to my deebot T9? is there a way to make it work? Many Thanks

**Comment by enter2name** [comment]
@gdgib 
I also have a DEEBOT X1 OMNI. I will try the next view days to get some information about the supported commands.

**Comment by enter2name** [comment]
@edenhaus 
By when does this merge have to be in the branch to be included in the Home Assistant patch tomorrow?
Refering to: https://github.com/DeebotUniverse/client.py/issues/612#issuecomment-2519957723

Thanks for the answer.

**Comment by edenhaus** [comment]
> @edenhaus By when does this merge have to be in the branch to be included in the Home Assistant patch tomorrow? Refering to: [#612 (comment)](https://github.com/DeebotUniverse/client.py/issues/612#issuecomment-2519957723)
> 
> Thanks for the answer.

Until tomorrow 12 CET.

@gdgib Please checkout https://github.com/DeebotUniverse/client.py/pull/611#issuecomment-2519670065 to get this PR merged as soon as possible.
If I had access to the fork, I could push the required changes myself. Otherwise please apply the provided diff

**Comment by gdgib** [comment]
@edenhaus added you to the fork AND updated the tests for good measure.  Thanks for the fast turn around.

@willliamchan if you look through the files in https://github.com/DeebotUniverse/client.py/tree/dev/deebot_client/hardware/deebot, you'll find a bunch are just one-line symlinks.  Ignore those for now.  Do any of the longer files go with a deebot model similar to the U2 Pro?  I ask because while the hack you're using will work for the basics, I don't think it's quite right since I think the X1 series and U2 series seem to have different features.  I strongly suggest opening an issue (https://github.com/DeebotUniverse/client.py/issues) for the U2 Pro if there isn't one already, since it's a separate device.  I might be able to help with this when I'm not on my lunch break.

**Review by edenhaus — APPROVED** [review]
Thanks @gdgib :+1:

**Comment by gdgib** [comment]
I'll make you a deal @willliamchan, if you open a separate issue so that we can keep each model to its own PR/issue, then I'll try to hack something together for you today.

All you have to do is go to [is create an issue](https://github.com/DeebotUniverse/client.py/discussions/new?category=general), and summarize the last two comments in it.  Heck you can even just paste links in there!

Honestly, if you don't do that I'll probably do that for you too, but it's a good habit to learn when you need something from an open source project to file a separate issue for each request.  It really helps our sanity.

**Comment by gdgib** [comment]
Thank you @edenhaus !  Can't tell you how much I appreciate all your hard work on this code base, and the integration.

**Pull request merged**
