### PR TITLE
Add support for GOAT G1 800 (White)

### PR DESCRIPTION
**Pull request by mback2k**
Follow up to #481 regarding white instead of grey model.

### CODE REVIEW

**Comment by edenhaus** [comment]
@mback2k Can you please fix the CI?

**Comment by mback2k** [comment]
> @mback2k Can you please fix the CI?

Ah, thanks for the hint. Should be fixed now.

**Review by edenhaus — APPROVED** [review]
Thanks 👍

**Comment by Rubeast** [comment]
Excuse me for the noob question. I see that this change for adding the class "guzput", which I also have, has been approved. 
Is there an other process to actually publish it? Since it is not yet working for me. Do I need to manually modify some files?

**Comment by mback2k** [comment]
No new release or inclusion into Home Assistant was performed yet. I guess we will have to wait until the July release.

**Pull request merged**
