### PR TITLE
Add Support for Deebot N8+

### PR DESCRIPTION
**Pull request by brendanm720**
Good Evening!

Trying this again!

Please merge this file to add support for the Deebot N8+.  I have tested this with my Deebot N8+ install and it seems to be working as expected.

Thank you.

## Summary by CodeRabbit

- **New Features**
	- Introduced comprehensive capabilities for the DEEBOT N8+ robot vacuum, including battery status retrieval, cleaning actions, and preference settings.
	- Added support for advanced features like continuous cleaning, fan speed adjustments, and map management.
	- Implemented error handling mechanisms to enhance user feedback and interaction.
	- Included the DEEBOT N8+ in the device test suite to ensure proper functionality and model loading.

### CODE REVIEW

**Review by edenhaus — APPROVED** [review]
Thanks @brendanm720 :+1:

**Comment by Qbertx78** [comment]
Hi everyone, I really appreciate your efforts to get our Deebots working with HA again. However, could you provide a unique procedure (the simplest possible) to understand, even for dumb users like me, how to fix these files?

**Comment by FelixHutnyk** [comment]
Just updated to the latest released which included this yet still running into:

`[homeassistant.components.ecovacs.controller] Device "DEEBOT N8+" not supported. More information at https://github.com/DeebotUniverse/client.py/issues/612: {'class': 'b2jqs4', 'company': 'eco-ng', 'did': 'f44bdd3f-0fd0-45b2-9f1e-703df650e312', 'name': 'E08642549C09HJZY0482', 'nick': '', 'resource': 'tshV', 'mqtt_connection': True, 'xmpp_connection': False, 'UILogicId': 'N8_PLUS', 'ota': True, 'icon': 'https://portal-ww.ecouser.net/api/pim/file/get/5feaeb27d4cb3a0006679047', 'model': 'N8_PLUS_BLACK', 'pip': '5fbc7cc69601440008b24469', 'deviceName': 'DEEBOT N8+', 'materialNo': '110-2029-0002', 'product_category': 'DEEBOT', 'status': 1}`

N8+ should be working with this?

**Comment by brendanm720** [comment]
> Just updated to the latest released which included this yet still running into:
> 
> ```
> [homeassistant.components.ecovacs.controller] Device "DEEBOT N8+" not supported. More information at https://github.com/DeebotUniverse/client.py/issues/612: {'class': 'b2jqs4', 'company': 'eco-ng', 'did': 'f44bdd3f-0fd0-45b2-9f1e-703df650e312', 'name': 'E08642549C09HJZY0482', 'nick': '', 'resource': 'tshV', 'mqtt_connection': True, 'xmpp_connection': False, 'UILogicId': 'N8_PLUS', 'ota': True, 'icon': 'https://portal-ww.ecouser.net/api/pim/file/get/5feaeb27d4cb3a0006679047', 'model': 'N8_PLUS_BLACK', 'pip': '5fbc7cc69601440008b24469', 'deviceName': 'DEEBOT N8+', 'materialNo': '110-2029-0002', 'product_category': 'DEEBOT', 'status': 1}
> ```
> 
> N8+ should be working with this?

it looks like the class id for the "black" version is different from the "white" version even though electronically *they're the same thing*. 

I will submit another PR for the black version for you.

**Comment by FelixHutnyk** [comment]
Amazing

Thank you so much!

> > Just updated to the latest released which included this yet still running into:
> > ```
> > [homeassistant.components.ecovacs.controller] Device "DEEBOT N8+" not supported. More information at https://github.com/DeebotUniverse/client.py/issues/612: {'class': 'b2jqs4', 'company': 'eco-ng', 'did': 'f44bdd3f-0fd0-45b2-9f1e-703df650e312', 'name': 'E08642549C09HJZY0482', 'nick': '', 'resource': 'tshV', 'mqtt_connection': True, 'xmpp_connection': False, 'UILogicId': 'N8_PLUS', 'ota': True, 'icon': 'https://portal-ww.ecouser.net/api/pim/file/get/5feaeb27d4cb3a0006679047', 'model': 'N8_PLUS_BLACK', 'pip': '5fbc7cc69601440008b24469', 'deviceName': 'DEEBOT N8+', 'materialNo': '110-2029-0002', 'product_category': 'DEEBOT', 'status': 1}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > N8+ should be working with this?
> 
> it looks like the class id for the "black" version is different from the "white" version even though electronically _they're the same thing_.
> 
> I will submit another PR for the black version for you.

**Pull request merged**
