### PR TITLE
Add support for Deebot T9 AIVI (8kwdb4)

### PR DESCRIPTION
**Pull request by townsmcp**
Adding PR to enable Deebot T9 Aivi (CN model/AliExpress) to work.
Will close out https://github.com/DeebotUniverse/client.py/issues/607#issue-2716875083

## Summary by CodeRabbit

- **New Features**
	- Introduced capabilities for the DEEBOT OZMO T9 AIVI, including advanced battery management, cleaning operations, custom command handling, fan speed control, lifespan tracking, mapping features, network information access, sound playback, and settings management.

- **Tests**
	- Expanded device testing coverage by adding the new DEEBOT model identifier to the existing test suite, ensuring all models are loaded correctly.

### CODE REVIEW

**Review by edenhaus — APPROVED** [review]
Thanks @townsmcp :+1:

**Comment by townsmcp** [comment]
> For the T9 AIVI eu #624, I did a Symlink to the T8 AIVI, and not a copy/paste [#612 (comment)](https://github.com/DeebotUniverse/client.py/issues/612#issuecomment-2521866376). I believe it's best to reduce the futur maintenance of multiple identical configuration. Maybe do the same for the T9 AIVI cn ?

@Yterz there are pro's and con's for doing a symlink - pro's are less maintenance in the future/inherit updates that are pushed to the original config, but con's are if an update is pushed to the original config that are not compatible with the other symlinked models there is a chance you can kill the integration for those linked model completely

**Comment by BloodyusHellus** [comment]
Do I correctly conclude that this fix will now also work for the EU version of the T9 AIVI (device code 659yh8) given the created symlink?

**Comment by edenhaus** [comment]
I'm fine with both (symlink or coping the file). I personally use a symlink if the file is identical and will copy it if the file is different than the other models but @townsmcp reasons are also correct (and accepted)

**Comment by townsmcp** [comment]
> Do I correctly conclude that this fix will now also work for the EU version of the T9 AIVI (device code 659yh8) given the created symlink?

@BloodyusHellus I dont think it would. My PR is for 8kwdb4 model. However @Yterz has submitted PR https://github.com/DeebotUniverse/client.py/pull/624#issue-2721666635 which covers your model

**Comment by BloodyusHellus** [comment]
> > Do I correctly conclude that this fix will now also work for the EU version of the T9 AIVI (device code 659yh8) given the created symlink?
> 
> @BloodyusHellus I dont think it would. My PR is for 8kwdb4 model. However @Yterz has submitted PR [#624 (comment)](https://github.com/DeebotUniverse/client.py/pull/624#issue-2721666635) which covers your model

Ah yes I see now, sorry for the confusion and thank you for your response :)

**Pull request merged**
