### PR TITLE
Added support for T9 PLUS (um2ywg)

### PR DESCRIPTION
**Pull request by marcolino7**
Here is Pull request to add T9+ um2ywg to supported device.
Set of command are from T8 AIVI.

## Summary by CodeRabbit

- **New Features**
	- Introduced comprehensive configuration for a robotic vacuum device, enhancing its capabilities including cleaning actions, battery status, fan speed control, and error handling.
	- Added advanced settings for features like carpet auto fan boost and sound playback adjustments.
- **Improvements**
	- Structured approach to managing device functionalities, ensuring better interaction with the vacuum's hardware and software.

### CODE REVIEW

**Comment by sh00t2kill** [comment]
FWIW confirmed this works

**Comment by marcolino7** [comment]
> FWIW confirmed this works

Hi, thanks for feedback. I don't know because merge failed

**Review by edenhaus — APPROVED** [review]
Thanks @marcolino7 :+1:

**Comment by Joey291** [comment]
I just Updates to HA 2024.12.2
With 9.3 Deebot Bit my T9+ still don't work

```

Logger: homeassistant.components.ecovacs.controller
Quelle: components/ecovacs/controller.py:100
Integration: Ecovacs (Dokumentation, Probleme)
Erstmals aufgetreten: 06:58:29 (1 Vorkommnisse)
Zuletzt protokolliert: 06:58:29

Device "DEEBOT T9+" not supported. More information at https://github.com/DeebotUniverse/client.py/issues/612: {'did': 'def7761d-bab4-41b1-9a39-ee20dd058e14', 'name': 'E03N00724C09HHBM0028', 'class': 'lhbd50', 'resource': 'eG7s', 'company': 'eco-ng', 'bindTs': 1698043779646, 'service': {'jmq': 'jmq-ngiot-eu.dc.ww.ecouser.net', 'mqs': 'api-ngiot.dc-eu.ww.ecouser.net'}, 'deviceName': 'DEEBOT T9+', 'icon': 'https://portal-ww.ecouser.net/api/pim/file/get/603f51243b03f50007b6c2ca', 'ota': True, 'UILogicId': 'T9_PRO_G', 'materialNo': '110-2010-1001', 'pid': '5f88195e6cf8de0008ed7c11', 'product_category': 'DEEBOT', 'model': 'DEEBOT_OZMO_T9PLUS', 'updateInfo': {'needUpdate': False, 'changeLog': ''}, 'nick': 'Schrotti', 'homeId': '626ba63b63a68e334831fc67', 'homeSort': 9999, 'status': 1, 'offmap': True, 'otaUpgrade': {}}

```

**Comment by marcolino7** [comment]
> I just Updates to HA 2024.12.2 With 9.3 Deebot Bit my T9+ still don't work
> 
> ```
> 
> Logger: homeassistant.components.ecovacs.controller
> Quelle: components/ecovacs/controller.py:100
> Integration: Ecovacs (Dokumentation, Probleme)
> Erstmals aufgetreten: 06:58:29 (1 Vorkommnisse)
> Zuletzt protokolliert: 06:58:29
> 
> Device "DEEBOT T9+" not supported. More information at https://github.com/DeebotUniverse/client.py/issues/612: {'did': 'def7761d...', 'name': 'E03N007....', 'class': 'lhbd50', 'resource': 'eG7s', 'company': 'eco-ng', 'bindTs': 16980437..., 'service': {'jmq': 'jmq-ngiot-eu.dc.ww.ecouser.net', 'mqs': 'api-ngiot.dc-eu.ww.ecouser.net'}, 'deviceName': 'DEEBOT T9+', 'icon': 'https://portal-ww.ecouser.net/api/pim/file/get/603f51243b03f50007b6c2ca', 'ota': True, 'UILogicId': 'T9_PRO_G', 'materialNo': '110-2...', 'pid': '5f88195e6cf8de...', 'product_category': 'DEEBOT', 'model': 'DEEBOT_OZMO_T9PLUS', 'updateInfo': {'needUpdate': False, 'changeLog': ''}, 'nick': 'Schrotti', 'homeId': '626ba63b63a68e...', 'homeSort': 9999, 'status': 1, 'offmap': True, 'otaUpgrade': {}}
> ```

Hi,
mine is working. What is your deviceID?

Marco

**Comment by Joey291** [comment]
> > I just Updates to HA 2024.12.2 With 9.3 Deebot Bit my T9+ still don't work
> 
> > 
> 
> > ```
> 
> > 
> 
> > Logger: homeassistant.components.ecovacs.controller
> 
> > Quelle: components/ecovacs/controller.py:100
> 
> > Integration: Ecovacs (Dokumentation, Probleme)
> 
> > Erstmals aufgetreten: 06:58:29 (1 Vorkommnisse)
> 
> > Zuletzt protokolliert: 06:58:29
> 
> > 
> 
> > Device "DEEBOT T9+" not supported. More information at https://github.com/DeebotUniverse/client.py/issues/612: {'did': 'def7761d...', 'name': 'E03N007....', 'class': 'lhbd50', 'resource': 'eG7s', 'company': 'eco-ng', 'bindTs': 16980437..., 'service': {'jmq': 'jmq-ngiot-eu.dc.ww.ecouser.net', 'mqs': 'api-ngiot.dc-eu.ww.ecouser.net'}, 'deviceName': 'DEEBOT T9+', 'icon': 'https://portal-ww.ecouser.net/api/pim/file/get/603f51243b03f50007b6c2ca', 'ota': True, 'UILogicId': 'T9_PRO_G', 'materialNo': '110-2...', 'pid': '5f88195e6cf8de...', 'product_category': 'DEEBOT', 'model': 'DEEBOT_OZMO_T9PLUS', 'updateInfo': {'needUpdate': False, 'changeLog': ''}, 'nick': 'Schrotti', 'homeId': '626ba63b63a68e...', 'homeSort': 9999, 'status': 1, 'offmap': True, 'otaUpgrade': {}}
> 
> > ```
> 
> 
> 
> Hi,
> 
> mine is working. What is your deviceID?
> 
> 
> 
> Marco

Hey 
Thanks for replying 
I Hope These 6 letters are the deviceid.


DEEBOT T9+ (lhbd50)
von Ecovacs
Firmware: 1.4.8
Seriennummer: E03N00724C09..

**Comment by marcolino7** [comment]
> > > I just Updates to HA 2024.12.2 With 9.3 Deebot Bit my T9+ still don't work
> > 
> > 
> > > 
> > 
> > 
> > > 
> > 
> > 
> > > 
> > 
> > 
> > > Logger: homeassistant.components.ecovacs.controller
> > 
> > 
> > > Quelle: components/ecovacs/controller.py:100
> > 
> > 
> > > Integration: Ecovacs (Dokumentation, Probleme)
> > 
> > 
> > > Erstmals aufgetreten: 06:58:29 (1 Vorkommnisse)
> > 
> > 
> > > Zuletzt protokolliert: 06:58:29
> > 
> > 
> > > 
> > 
> > 
> > > Device "DEEBOT T9+" not supported. More information at #612: {'did': 'def7761d...', 'name': 'E03N007....', 'class': 'lhbd50', 'resource': 'eG7s', 'company': 'eco-ng', 'bindTs': 16980437..., 'service': {'jmq': 'jmq-ngiot-eu.dc.ww.ecouser.net', 'mqs': 'api-ngiot.dc-eu.ww.ecouser.net'}, 'deviceName': 'DEEBOT T9+', 'icon': 'https://portal-ww.ecouser.net/api/pim/file/get/603f51243b03f50007b6c2ca', 'ota': True, 'UILogicId': 'T9_PRO_G', 'materialNo': '110-2...', 'pid': '5f88195e6cf8de...', 'product_category': 'DEEBOT', 'model': 'DEEBOT_OZMO_T9PLUS', 'updateInfo': {'needUpdate': False, 'changeLog': ''}, 'nick': 'Schrotti', 'homeId': '626ba63b63a68e...', 'homeSort': 9999, 'status': 1, 'offmap': True, 'otaUpgrade': {}}
> > 
> > 
> > > 
> > 
> > 
> > Hi,
> > mine is working. What is your deviceID?
> > Marco
> 
> Hey Thanks for replying I Hope These 6 letters are the deviceid.
> 
> DEEBOT T9+ (lhbd50) von Ecovacs Firmware: 1.4.8 Seriennummer: E03N00724C09..

Hi device Id is different from mine T9+ that is um2ywg
Perhaps yours work fine with T8 template as mine. You can Symlink the T8 file x5d34r.py to your lhbd50.py and create a pull request in order to add. You can also quick test with this command in Home Assistant Console:

```
from HA console type login, when you got shell type this commands
docker ps | grep homeassistant
docker exec -it <CONTAINERID> sh (retrived with previus command)
cd /usr/local/lib/python3.13/site-packages/deebot_client/hardware/deebot
ln -svfT x5d34r.py lhbd50.py 

restart home assistant
```

This create a symlink to your robot using the T8 set of commands. Please perform a backup o a snapshot of your HA installation, you use these commands at your own risk.

Marco

**Comment by xiaowang0017** [comment]
日志记录器: homeassistant.components.ecovacs.controller
来源: components/ecovacs/controller.py:100
集成: Ecovacs (文档, 问题)
首次出现: 22:09:30 (1 次出现)
上次记录: 22:09:30

Device "DEEBOT N9+" not supported. More information at [https://github.com/DeebotUniverse/client.py/issues/612: Issues · DeebotUniverse/client.py](https://github.com/DeebotUniverse/client.py/issues/612:) Issues · DeebotUniverse/client.py   {'did': '56ae434d-3f52-4e87-9a9b-b962894cd447', 'name': 'E25214790C00YJ6V0436', 'class': 'a7lhb1', 'resource': 'rvMh', 'company': 'eco-ng', 'bindTs': 1754486360071, 'service': {'jmq': 'jmq-ngiot-cn.dc.cn.ecouser.net', 'mqs': 'api-ngiot.dc-cn.cn.ecouser.net'}, 'deviceName': 'DEEBOT N9+', 'icon': '[https://portal.ecouser.net/api/pim/file/get/603f50064ec6fe0008f6c257 ](https://portal.ecouser.net/api/pim/file/get/603f50064ec6fe0008f6c257)  ', 'ota': True, 'UILogicId': 'DK_850_CN', 'materialNo': '130-6224-1301', 'pid': '5f911e2fb789620008056fd2', 'product_category': 'DEEBOT', 'model': 'N9_PLUS', 'updateInfo': {'needUpdate': False, 'changeLog': ''}, 'nick': '小宝', 'homeId': '6260f3234f20d923f82011d2', 'homeSort': 1, 'status': 1, 'otaUpgrade': {}}

**Pull request merged**
